### ISSUE TITLE
 [Feature Request] Random draw from search pool

### ISSUE THREAD

**Issue by QnF6eq** [funmaker/Hybooru#24]
This is a feature request:
I like the idea of a Random function that uses the results of the search as the pool to draw from instead of the whole database.
Meaning that if a user has some "Tag1 -Tag2" in their searchbar and clicked on Random they would only get posts that are compliant with that search. 
For QoL the search input would need to be carried over to the next random post's searchbar as to allow an "endless-mode" so to say.

**Comment by funmaker** [comment]
Because of how searches are implemented this feature will not be easy to add for now and I'm uncertain of how intuitive it would be. I could add a button that gives you random post for a single tag though if that'd cover your usecase. That functionality is already implemented as motd and could easily be extended by adding a new button next to "Search" when a single tag is selected like "I'm feeling lucky" in google.

**Comment by funmaker** [comment]
Added in v1.8.0
